version: "3.8"

x-container: &container
    image: anton1307d/laravel-tig
    volumes:
        - .:/var/www/html:cached
        - ~/.config:/var/www/.config
    env_file:
        - .env
    networks:
        - tig
    depends_on:
        - mysql_master
        - redis

x-environment: &environment
    # php configuration
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    PHP_XDEBUG_REMOTE_ENABLE: 1
    PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
    PHP_XDEBUG_REMOTE_PORT: 9000
    PHP_XDEBUG_MODE: debug

services:
    app:
        <<: *container
        environment:
            <<: *environment
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            target: develop
            args:
                - USER_UID=${USER_UID:-1000}
                - USER_GID=${USER_GID:-1000}
        ports:
            - "127.0.0.1:80:80/tcp"
        networks:
            - tig

    nginx:
        image: nginx:latest
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - ./.infra/nginx-cache.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - tig

    scheduler:
        <<: *container
        environment:
            <<: *environment
            CONTAINER_ROLE: scheduler

    queue:
        <<: *container
        environment:
            <<: *environment
            CONTAINER_ROLE: queue

    redis:
        image: redis:6-alpine
        networks:
            - tig
        volumes:
            - redis:/data

    mysql_master:
        image: mysql:8.0
        env_file:
            - ./.infra/mysql/master/mysql_master.env
        container_name: "mysql_master"
        command: >-
            --default-authentication-plugin=mysql_native_password
            --sql-require-primary-key=OFF
        restart: "no"
        ports:
            - 4406:3306
        volumes:
            - ./.infra/mysql/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
            - ./.infra/mysql/master/data:/var/lib/mysql
        networks:
            - tig

    mysql_slave:
        image: mysql:8.0
        command: >-
            --default-authentication-plugin=mysql_native_password
            --sql-require-primary-key=OFF
        env_file:
            - ./.infra/mysql/slave/mysql_slave.env
        container_name: "mysql_slave"
        restart: "no"
        ports:
            - 5506:3306
        depends_on:
            - mysql_master
        volumes:
            - ./.infra/mysql/slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
            - ./.infra/mysql/slave/data:/var/lib/mysql
        networks:
            - tig

    mysql_slave_2:
        image: mysql:8.0
        command: >-
            --default-authentication-plugin=mysql_native_password
            --sql-require-primary-key=OFF
        env_file:
            - ./.infra/mysql/slave_2/mysql_slave.env
        container_name: "mysql_slave_2"
        restart: "no"
        ports:
            - 6506:3306
        depends_on:
            - mysql_master
        volumes:
            - ./.infra/mysql/slave_2/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
            - ./.infra/mysql/slave_2/data:/var/lib/mysql
        networks:
            - tig

volumes:
    redis:
        driver: local
    elastic:
        driver: local
    grafana_data:
        driver: local
    influxdb_data:
        driver: local
    mongodb_data:
        driver: local
    esdata:
        driver: local

networks:
    tig:
        name: tig
