version: "3.8"

x-container: &container
  image: localhost:5000/antonzubb/virtrex:tmp
  volumes:
    - ./.:/var/www/html:cached
  depends_on:
    - mysql
    - redis

x-environment: &environment
  # php configuration
  PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
  APP_ENV: testing
  APP_KEY: dca929db9304b6e9543380c3586290e8
  DB_HOST: mysql
  DB_DATABASE: testing
  DB_USERNAME: testing
  DB_PASSWORD: secret
  REDIS_HOST: redis
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  NPM_TOKEN: ${NPM_TOKEN}
  REDIS_CACHE_HOST: redis
  REDIS_CACHE_PASSWORD: null
  REDIS_CACHE_PORT: 6379

services:
  app:
    <<: *container
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: develop
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
        - COMPOSER_AUTH=${COMPOSER_AUTH}
    environment:
      <<: *environment
    volumes:
      - ./.:/var/www/html:cached
      - composer_cache:/var/www/.composer
    depends_on:
      mysql:
        condition: service_healthy

  app-test:
    <<: *container
    environment:
      <<: *environment

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data

  mysql:
    image: mysql:8
    command: "--performance-schema=OFF --innodb_flush_log_at_trx_commit=2 --innodb_log_buffer_size=4M --innodb_buffer_pool_size=128M"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/overrides/mysql:/docker-entrypoint-initdb.d/
    tmpfs:
      - /tmp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_USER: ${DB_USERNAME:-database}
      MYSQL_PASSWORD: ${DB_PASSWORD:-database}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  yarn_cache:
  composer_cache:
  mysql:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
