name: Main Deployment

on:
  push:
    branches:
      - main


env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

jobs:
  packaging:
    name: Packaging
    runs-on: [ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Git clean and copy files
        run: |
          git clean -x -d -f .
          cp .env.example .env

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/app/Dockerfile
          build-args: |
            COMPOSER_AUTH
          push: true
          tags: anton1307d/laravel-tig:main, anton1307d/laravel-tig:${{ github.run_id }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: production
